/// Flutter icons AppIcons
/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AppIcons
///      fonts:
///       - asset: fonts/AppIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class AppIcons {
  AppIcons._();

  static const _kFontFam = 'AppIcons';
  static const String? _kFontPkg = null;

  static const IconData accept = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData account = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData back = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData download = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData exit = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData google = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData landscape = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData note = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData person = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData person_add = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData refresh = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sort = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData web = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
